# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ijkplayerStudyDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ijkplayerStudyDemo

    pod 'LFLiveKit'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'YYModel'
    pod 'SDAutoLayout'
    
end
